export const featuredPortfolio = [
  {
    id: 1,
    title: "E-commerce web App",
    img: "https://raw.githubusercontent.com/Rzied/Wesh-VueJs/main/assets/img/Des1.png",
    source: "https://github.com/Rzied/Wesh-VueJs",
    info: " L'application Wesh est une imitation de la plateforme de E-commerce Wish sur laquelle j'ai monté en compétence sur le framework VueJS",
    demo: "https://rzied.github.io/Wesh-VueJs/",
  },
  {
    id: 2,
    title: "Rampa UI Design",
    img: "https://cdn.dribbble.com/users/702789/screenshots/15054318/media/4ea5d492b7b07eebc9528ff960794879.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 3,
    title: "E-commerce Web Design",
    img: "https://cdn.dribbble.com/users/1387827/screenshots/15466426/media/deb2dca6762cd3610321c98bfccb0b72.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 4,
    title: "Relax Mobile App",
    img: "https://cdn.dribbble.com/users/4095861/screenshots/15467417/media/d6a15c416626f12b31fa5ca1db192572.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 5,
    title: "Hero Web Design",
    img: "https://cdn.dribbble.com/users/5031392/screenshots/15467520/media/c36b3b15b25b1e190d081abdbbf947cf.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 6,
    title: "Banking App",
    img: "https://cdn.dribbble.com/users/3307260/screenshots/15468444/media/447b4501f7a145b05e11c70199a9c417.jpg?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
];

export const frameworksPortfolio = [
  {
    id: 1,
    title: "Web Social Media App",
    img: "https://cdn.dribbble.com/users/5031392/screenshots/15467520/media/c36b3b15b25b1e190d081abdbbf947cf.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 2,
    title: "Web Rampa UI Design",
    img: "https://cdn.dribbble.com/users/3967258/screenshots/15463803/media/4fddb9a2caf3b3bd634060f706a91e73.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 3,
    title: "Web E-commerce Design",
    img: "https://cdn.dribbble.com/users/3637068/screenshots/15467010/media/69a3279182b75365013fe285733d1122.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 4,
    title: "Web Relax App",
    img: "https://cdn.dribbble.com/users/2264844/screenshots/15463998/media/d85e92a332c41094f68e1f716884f7ce.jpg?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 5,
    title: "Web Design",
    img: "https://cdn.dribbble.com/users/387658/screenshots/15458608/media/e92ec1dd33dd1170ae3dc9c5272f2693.jpg?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 6,
    title: "Web Banking App",
    img: "https://cdn.dribbble.com/users/6384483/screenshots/15468426/media/ce9479fa1f8dba3a4a49840d76e55e31.png?compress=1&resize=1200x900",
    source: "",
    info: "",
    demo: "",
  },
];

export const jSPortfolio = [
  {
    id: 1,
    title: "The Game of Pig",
    img: "https://raw.githubusercontent.com/Rzied/PigGame/main/Screenshot_1.png",
    source: "https://github.com/Rzied/PigGame",
    info: "C'est un jeu de dé, où deux joueurs se relaient pour lancer un seul dé autant de fois qu'ils le souhaitent, font la course pour atteindre 100 points. C'est une petite web app développer en JavaScript.  ",
    demo: "https://rzied.github.io/PigGame/",
  },
  {
    id: 2,
    title: "Guess My Number Game",
    img: "https://raw.githubusercontent.com/Rzied/GuessMyNumber/main/search.png",
    source: "https://github.com/Rzied/GuessMyNumber",
    info: "Guess my number est un jeu qui repose sur le principe de deviner un chiffre choisis aléatoirement (entre 1 et 20), c'est une petite web app développer en JavaScript. ",
    demo: "https://rzied.github.io/GuessMyNumber/",
  },
  {
    id: 3,
    title: "Application bancaire en ligne",
    img: "https://raw.githubusercontent.com/Rzied/Bankist/main/img/Screenshot_1.png",
    source: "https://github.com/Rzied/Bankist",
    info: "Bankist est une application bancaire en ligne qui sert à montrer les différents services de cette banque et de mettre en avant ces point forts avec un peu de marketing... avec une petite form d'inscription le tout développer en JavaScript.",
    demo: "https://rzied.github.io/Bankist/",
  },
  {
    id: 4,
    title: "Jeu de Memory",
    img: "https://raw.githubusercontent.com/Rzied/MemoryJeu/main/Memory.png",
    source: "https://github.com/Rzied/MemoryJeu",
    info: "C'est un petit projet où j’ai pratiqué ce que j’ai appris sur le JavaScript quand j’ai commencé à apprendre le web dynamique, qui représente le vrai jeu de carte memory. Il suffit de retourner la carte, et de trouver le visuel identique ! ",
    demo: "https://rzied.github.io/MemoryJeu/",
  },
  {
    id: 5,
    title: "Regex sur un formulaire",
    img: "https://raw.githubusercontent.com/Rzied/RegexForm/main/form.png",
    source: "https://github.com/Rzied/RegexForm",
    info: "C'est un formulaire développer en JavaScript dans lequel je mets en pratique ce que j’ai sur le Regex pour valider les champs avant de confirmer l'envoie.",
    demo: "https://rzied.github.io/RegexForm/",
  },
  {
    id: 6,
    title: "Jeu de Taquin",
    img: "https://raw.githubusercontent.com/Rzied/JeuTaquin/main/Taq.png",
    source: "https://github.com/Rzied/JeuTaquin",
    info: "Ce projet représente Le taquin qui est un jeu solitaire en forme de damier (3x3). Je l’ai développé pour mettre en pratique le phénomène de drag & drop de JavaScript.",
    demo: "https://rzied.github.io/JeuTaquin/",
  },
];

export const phpPortfolio = [
  {
    id: 1,
    title: "Design Social Media App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 2,
    title: "Design Rampa UI Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 3,
    title: "Design E-commerce Web Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 4,
    title: "Design Relax Mobile App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 5,
    title: "Design Keser Web Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 6,
    title: "Design Banking App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
];

export const contentPortfolio = [
  {
    id: 1,
    title: "Content Social Media App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 2,
    title: "Content Rampa UI Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 3,
    title: "Content E-commerce Web Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 4,
    title: "Content Relax Mobile App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 5,
    title: "Content Keser Web Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
  {
    id: 6,
    title: "Content Banking App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    source: "",
    info: "",
    demo: "",
  },
];
